version: '3'
services:
  redis:
    image: redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/data
      - $PWD/redis-config/redis.conf:/usr/local/etc/redis/redis.conf
  
  consul:
    image: consul
    ports:
      - "8500:8500"
    volumes:
      - $PWD/consul-data:/consul/data
  
  pulsar:
    image: apachepulsar/pulsar:2.4.1
    command: "bin/pulsar standalone"
    ports:
      - 6650:6650
      - 8080:8080
    volumes:
      - $PWD/pulsar-data:/pulsar/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
